### Анализ игр NBA

Подготовил Григорий Крюков

Источник данных: https://www.kaggle.com/datasets/nathanlauga/nba-games

In [1]:
import numpy as np
import pandas as pd
from tqdm import tqdm
from datetime import datetime

In [2]:
N = 30
df = pd.read_csv("games.csv")
df["date"] = [datetime.strptime(df.GAME_DATE_EST[i], "%Y-%m-%d") for i in range(len(df))]
df = df.sort_values('date')
df

GAME_DATE_EST   GAME_ID GAME_STATUS_TEXT  HOME_TEAM_ID  VISITOR_TEAM_ID  \
18433    2003-10-05  10300001            Final    1610612762       1610612742   
18432    2003-10-06  10300002            Final    1610612763       1610612749   
18425    2003-10-07  10300010            Final    1610612764       1610612752   
18424    2003-10-07  10300006            Final    1610612747       1610612744   
18427    2003-10-07  10300004            Final    1610612742       1610612753   
...             ...       ...              ...           ...              ...   
5        2022-03-12  22101010            Final    1610612762       1610612758   
4        2022-03-12  22101009            Final    1610612743       1610612761   
3        2022-03-12  22101008            Final    1610612744       1610612749   
1        2022-03-12  22101006            Final    1610612741       1610612739   
0        2022-03-12  22101005            Final    1610612748       1610612750   

       SEASON  TEAM_ID_home  PTS_home  FG_PCT_home  FT_PCT_home  ...  \
18433    2003    1610612762      90.0        0.457        0.735  ...   
18432    2003    1610612763     105.0        0.494        0.618  ...   
18425    2003    1610612764     104.0        0.506        0.677  ...   
18424    2003    1610612747       NaN          NaN          NaN  ...   
18427    2003    1610612742      99.0        0.488        0.667  ...   
...       ...           ...       ...          ...          ...  ...   
5        2021    1610612762     134.0        0.558        0.710  ...   
4        2021    1610612743     115.0        0.551        0.750  ...   
3        2021    1610612744     122.0        0.484        0.933  ...   
1        2021    1610612741     101.0        0.443        0.933  ...   
0        2021    1610612748     104.0        0.398        0.760  ...   

       REB_home  TEAM_ID_away  PTS_away  FG_PCT_away  FT_PCT_away  \
18433      41.0    1610612742      85.0        0.447        0.500   
18432      48.0    1610612749      94.0        0.427        0.700   
18425      45.0    1610612752      86.0        0.380        0.852   
18424       NaN    1610612744       NaN          NaN          NaN   
18427      52.0    1610612753      89.0        0.408        0.727   
...         ...           ...       ...          ...          ...   
5          44.0    1610612758     125.0        0.500        0.857   
4          39.0    1610612761     127.0        0.471        0.760   
3          55.0    1610612749     109.0        0.413        0.696   
1          46.0    1610612739      91.0        0.419        0.824   
0          53.0    1610612750     113.0        0.422        0.875   

       FG3_PCT_away  AST_away  REB_away  HOME_TEAM_WINS       date  
18433         0.250      20.0      38.0               1 2003-10-05  
18432         0.154      20.0      43.0               1 2003-10-06  
18425         0.188      19.0      37.0               1 2003-10-07  
18424           NaN       NaN       NaN               0 2003-10-07  
18427         0.350      15.0      34.0               1 2003-10-07  
...             ...       ...       ...             ...        ...  
5             0.394      27.0      33.0               1 2022-03-12  
4             0.387      28.0      50.0               0 2022-03-12  
3             0.386      27.0      39.0               1 2022-03-12  
1             0.208      19.0      40.0               1 2022-03-12  
0             0.357      21.0      46.0               0 2022-03-12  

[25796 rows x 22 columns]

In [3]:
moods = np.ones(N)
moods_h = np.zeros(len(df))
moods_v = np.zeros(len(df))
k = 1610612737
for i in range(len(df)):
    home = df.HOME_TEAM_ID.iloc[i] - k
    visitor = df.VISITOR_TEAM_ID.iloc[i] - k
    moods_h[i] = moods[home]
    moods_v[i] = moods[visitor]
    if df.HOME_TEAM_WINS.iloc[i] == 1:
        moods[home] = 1
        moods[visitor] = 0
    else:
        moods[home] = 0
        moods[visitor] = 1
df['moods_h'] = moods_h
df['moods_v'] = moods_v
df['moods_diff'] = moods_h - moods_v
df

GAME_DATE_EST   GAME_ID GAME_STATUS_TEXT  HOME_TEAM_ID  VISITOR_TEAM_ID  \
18433    2003-10-05  10300001            Final    1610612762       1610612742   
18432    2003-10-06  10300002            Final    1610612763       1610612749   
18425    2003-10-07  10300010            Final    1610612764       1610612752   
18424    2003-10-07  10300006            Final    1610612747       1610612744   
18427    2003-10-07  10300004            Final    1610612742       1610612753   
...             ...       ...              ...           ...              ...   
5        2022-03-12  22101010            Final    1610612762       1610612758   
4        2022-03-12  22101009            Final    1610612743       1610612761   
3        2022-03-12  22101008            Final    1610612744       1610612749   
1        2022-03-12  22101006            Final    1610612741       1610612739   
0        2022-03-12  22101005            Final    1610612748       1610612750   

       SEASON  TEAM_ID_home  PTS_home  FG_PCT_home  FT_PCT_home  ...  \
18433    2003    1610612762      90.0        0.457        0.735  ...   
18432    2003    1610612763     105.0        0.494        0.618  ...   
18425    2003    1610612764     104.0        0.506        0.677  ...   
18424    2003    1610612747       NaN          NaN          NaN  ...   
18427    2003    1610612742      99.0        0.488        0.667  ...   
...       ...           ...       ...          ...          ...  ...   
5        2021    1610612762     134.0        0.558        0.710  ...   
4        2021    1610612743     115.0        0.551        0.750  ...   
3        2021    1610612744     122.0        0.484        0.933  ...   
1        2021    1610612741     101.0        0.443        0.933  ...   
0        2021    1610612748     104.0        0.398        0.760  ...   

       FG_PCT_away  FT_PCT_away  FG3_PCT_away  AST_away  REB_away  \
18433        0.447        0.500         0.250      20.0      38.0   
18432        0.427        0.700         0.154      20.0      43.0   
18425        0.380        0.852         0.188      19.0      37.0   
18424          NaN          NaN           NaN       NaN       NaN   
18427        0.408        0.727         0.350      15.0      34.0   
...            ...          ...           ...       ...       ...   
5            0.500        0.857         0.394      27.0      33.0   
4            0.471        0.760         0.387      28.0      50.0   
3            0.413        0.696         0.386      27.0      39.0   
1            0.419        0.824         0.208      19.0      40.0   
0            0.422        0.875         0.357      21.0      46.0   

       HOME_TEAM_WINS       date  moods_h  moods_v  moods_diff  
18433               1 2003-10-05      1.0      1.0         0.0  
18432               1 2003-10-06      1.0      1.0         0.0  
18425               1 2003-10-07      1.0      1.0         0.0  
18424               0 2003-10-07      1.0      1.0         0.0  
18427               1 2003-10-07      0.0      1.0        -1.0  
...               ...        ...      ...      ...         ...  
5                   1 2022-03-12      0.0      0.0         0.0  
4                   0 2022-03-12      0.0      1.0        -1.0  
3                   1 2022-03-12      1.0      1.0         0.0  
1                   1 2022-03-12      1.0      0.0         1.0  
0                   0 2022-03-12      1.0      0.0         1.0  

[25796 rows x 25 columns]

Сила команд

In [4]:
w = np.zeros(N)
prev_win = [1 for i in range(N)] # Выиграна ли предыдущая игра
A = [np.zeros((2, 2)) for i in range(N)] # Матрицы переходов
k = 1610612737 # Параметр, вычитание которого из id команды приводит к порядковому номеру
# Проходимся циклом с конца таблицы (в хронологическом порядке), заполняем соответствующие значения матриц переходов
for i in range(len(df)):
    home = df.HOME_TEAM_ID.iloc[i] - k
    visitor = df.VISITOR_TEAM_ID.iloc[i] - k
    if df.HOME_TEAM_WINS.iloc[i] == 1:
        A[home][1 - prev_win[home]][0] += 1
        A[visitor][1 - prev_win[visitor]][1] += 1
        prev_win[home] = 1
        prev_win[visitor] = 0
    else:
        A[home][1 - prev_win[home]][1] += 1
        A[visitor][1 - prev_win[visitor]][0] += 1
        prev_win[home] = 0
        prev_win[visitor] = 1
        
# Теперь поделим число выигранных матчей на число всех матчей
for i in range(N):
    w[i] = A[i].sum(axis=1)[0] / A[i].sum()
    
w_base = w.copy()

In [5]:
w

array([0.46647399, 0.55733186, 0.5107832 , 0.45656081, 0.50495627,
       0.57126568, 0.55779183, 0.56203545, 0.56357388, 0.51618497,
       0.52044818, 0.56721311, 0.47755102, 0.4004884 , 0.44183314,
       0.40256567, 0.44791054, 0.52036718, 0.45147929, 0.51665693,
       0.49853372, 0.41005451, 0.64105379, 0.52561888, 0.51515152,
       0.53962704, 0.49853544, 0.43506494, 0.48242075, 0.40103159])

In [6]:
N = 30
prev_win = [1 for i in range(N)] # Выиграна ли предыдущая игра
TM = [np.zeros((2, 2)) for i in range(N)] # Матрицы переходов
k = 1610612737 # Параметр, вычитание которого из id команды приводит к порядковому номеру
# Проходимся циклом с конца таблицы (в хронологическом порядке), заполняем соответствующие значения матриц переходов
for i in range(len(df)):
    home = df.HOME_TEAM_ID.iloc[i] - k
    visitor = df.VISITOR_TEAM_ID.iloc[i] - k
    if df.HOME_TEAM_WINS.iloc[i] == 1:
        TM[home][1 - prev_win[home]][0] += 1
        TM[visitor][1 - prev_win[visitor]][1] += 1
        prev_win[home] = 1
        prev_win[visitor] = 0
    else:
        TM[home][1 - prev_win[home]][1] += 1
        TM[visitor][1 - prev_win[visitor]][0] += 1
        prev_win[home] = 0
        prev_win[visitor] = 1
        
# Теперь нам осталось получить "настоящие" оценки матриц переходов
# Для этого все строки матриц TM нормируем так, чтобы сумма по строкам была равна 1
for i in range(N):
    TM[i][0] /= TM[i][0].sum()
    TM[i][1] /= TM[i][1].sum()
    
TM_base = TM.copy()

In [7]:
TM[11]

array([[0.57899807, 0.42100193],
       [0.55050505, 0.44949495]])

Сила команд по сезонам

In [8]:
df[df.SEASON == 2007]

GAME_DATE_EST   GAME_ID GAME_STATUS_TEXT  HOME_TEAM_ID  VISITOR_TEAM_ID  \
12835    2007-10-06  10700001            Final    1610612738       1610612761   
12834    2007-10-08  10700006            Final    1610612765       1610612748   
12833    2007-10-08  10700005            Final    1610612753       1610612737   
12827    2007-10-09  10700008            Final    1610612749       1610612741   
12826    2007-10-09  10700007            Final    1610612739       1610612764   
...             ...       ...              ...           ...              ...   
11429    2008-06-08  40700402            Final    1610612738       1610612747   
11428    2008-06-10  40700403            Final    1610612747       1610612738   
11427    2008-06-12  40700404            Final    1610612747       1610612738   
11426    2008-06-15  40700405            Final    1610612747       1610612738   
11425    2008-06-17  40700406            Final    1610612738       1610612747   

       SEASON  TEAM_ID_home  PTS_home  FG_PCT_home  FT_PCT_home  ...  \
12835    2007    1610612738      89.0        0.461        0.696  ...   
12834    2007    1610612765     103.0        0.479        0.714  ...   
12833    2007    1610612753      93.0        0.413        0.560  ...   
12827    2007    1610612749      93.0        0.417        0.651  ...   
12826    2007    1610612739      62.0        0.306        0.800  ...   
...       ...           ...       ...          ...          ...  ...   
11429    2007    1610612738     108.0        0.529        0.711  ...   
11428    2007    1610612747      87.0        0.435        0.618  ...   
11427    2007    1610612747      91.0        0.416        0.724  ...   
11426    2007    1610612747     103.0        0.456        0.742  ...   
11425    2007    1610612738     131.0        0.494        0.865  ...   

       FG_PCT_away  FT_PCT_away  FG3_PCT_away  AST_away  REB_away  \
12835        0.388        0.625         0.321      21.0      41.0   
12834        0.403        0.739         0.389      22.0      35.0   
12833        0.408        0.702         0.429      19.0      39.0   
12827        0.485        0.600         0.500      24.0      38.0   
12826        0.354        0.690         0.357      17.0      42.0   
...            ...          ...           ...       ...       ...   
11429        0.494        1.000         0.476      20.0      36.0   
11428        0.349        0.682         0.444      19.0      45.0   
11427        0.452        0.821         0.364      15.0      40.0   
11426        0.429        0.774         0.364      20.0      37.0   
11425        0.422        0.737         0.370      16.0      29.0   

       HOME_TEAM_WINS       date  moods_h  moods_v  moods_diff  
12835               1 2007-10-06      0.0      0.0         0.0  
12834               1 2007-10-08      0.0      0.0         0.0  
12833               0 2007-10-08      0.0      1.0        -1.0  
12827               1 2007-10-09      0.0      0.0         0.0  
12826               0 2007-10-09      0.0      0.0         0.0  
...               ...        ...      ...      ...         ...  
11429               1 2008-06-08      1.0      0.0         1.0  
11428               1 2008-06-10      0.0      1.0        -1.0  
11427               0 2008-06-12      1.0      0.0         1.0  
11426               1 2008-06-15      0.0      1.0        -1.0  
11425               1 2008-06-17      0.0      1.0        -1.0  

[1411 rows x 25 columns]

In [9]:
w_seasons = []
for s in range(2004, 2022):
    w = np.zeros(N)
    prev_win = [1 for i in range(N)] # Выиграна ли предыдущая игра
    A = [np.zeros((2, 2)) for i in range(N)] # Матрицы переходов
    k = 1610612737 # Параметр, вычитание которого из id команды приводит к порядковому номеру
    # Проходимся циклом с конца таблицы (в хронологическом порядке), заполняем соответствующие значения матриц переходов
    dt = df[df.SEASON == s]
    for i in range(len(dt)):
        home = dt.HOME_TEAM_ID.iloc[i] - k
        visitor = dt.VISITOR_TEAM_ID.iloc[i] - k
        if dt.HOME_TEAM_WINS.iloc[i] == 1:
            A[home][1 - prev_win[home]][0] += 1
            A[visitor][1 - prev_win[visitor]][1] += 1
            prev_win[home] = 1
            prev_win[visitor] = 0
        else:
            A[home][1 - prev_win[home]][1] += 1
            A[visitor][1 - prev_win[visitor]][0] += 1
            prev_win[home] = 0
            prev_win[visitor] = 1
        
    # Теперь поделим число выигранных матчей на число всех матчей
    for i in range(N):
        w[i] = A[i].sum(axis=1)[0] / A[i].sum()
        
    w_seasons.append(w)

In [10]:
w_seasons

[array([0.16666667, 0.54347826, 0.51190476, 0.22352941, 0.56043956,
        0.67676768, 0.60869565, 0.42352941, 0.6043956 , 0.44186047,
        0.43373494, 0.72      , 0.38095238, 0.53488372, 0.5       ,
        0.41860465, 0.46428571, 0.54      , 0.52222222, 0.75      ,
        0.3255814 , 0.58241758, 0.72222222, 0.625     , 0.41860465,
        0.3255814 , 0.53409091, 0.53684211, 0.64864865, 0.23529412]),
 array([0.33707865, 0.4       , 0.61165049, 0.46067416, 0.48958333,
        0.71681416, 0.55789474, 0.41573034, 0.46067416, 0.59405941,
        0.56701031, 0.63392857, 0.47368421, 0.42222222, 0.59405941,
        0.29213483, 0.46590909, 0.51041667, 0.47191011, 0.64545455,
        0.26666667, 0.52083333, 0.69902913, 0.42696629, 0.34831461,
        0.48314607, 0.59139785, 0.5       , 0.73148148, 0.32222222]),
 array([0.38888889, 0.31111111, 0.58715596, 0.46067416, 0.62      ,
        0.76041667, 0.54255319, 0.53535354, 0.63541667, 0.51136364,
        0.50526316, 0.50537634, 0.35555556, 

In [11]:
TM_seasons = []
for s in range(2004, 2022):
    w = np.zeros(N)
    prev_win = [1 for i in range(N)] # Выиграна ли предыдущая игра
    A = [np.zeros((2, 2)) for i in range(N)] # Матрицы переходов
    k = 1610612737 # Параметр, вычитание которого из id команды приводит к порядковому номеру
    # Проходимся циклом с конца таблицы (в хронологическом порядке), заполняем соответствующие значения матриц переходов
    dt = df[df.SEASON == s]
    for i in range(len(dt)):
        home = dt.HOME_TEAM_ID.iloc[i] - k
        visitor = dt.VISITOR_TEAM_ID.iloc[i] - k
        if dt.HOME_TEAM_WINS.iloc[i] == 1:
            A[home][1 - prev_win[home]][0] += 1
            A[visitor][1 - prev_win[visitor]][1] += 1
            prev_win[home] = 1
            prev_win[visitor] = 0
        else:
            A[home][1 - prev_win[home]][1] += 1
            A[visitor][1 - prev_win[visitor]][0] += 1
            prev_win[home] = 0
            prev_win[visitor] = 1
            
    # Теперь нам осталось получить "настоящие" оценки матриц переходов
    # Для этого все строки матриц TM нормируем так, чтобы сумма по строкам была равна 1
    for i in range(N):
        A[i][0] /= A[i][0].sum()
        A[i][1] /= A[i][1].sum()
    TM_seasons.append(A)

In [12]:
TM_seasons[0][29]

array([[0.2       , 0.8       ],
       [0.24615385, 0.75384615]])

Стандартная модель

In [13]:
y_true = np.array(df.HOME_TEAM_WINS)

In [14]:
k = 1610612737
y_pred = np.zeros(len(df))
for i in range(len(df)):
    home = df.HOME_TEAM_ID.iloc[i] - k
    visitor = df.VISITOR_TEAM_ID.iloc[i] - k
    if w_base[home] > w_base[visitor]:
        y_pred[i] = 1

In [15]:
np.abs(y_pred - y_true).mean()

0.436501783222205

In [16]:
k = 1610612737
y_pred = np.zeros(len(df))
for i in range(len(df)):
    home = df.HOME_TEAM_ID.iloc[i] - k
    visitor = df.VISITOR_TEAM_ID.iloc[i] - k
    w_h = TM[home][int(df.moods_h.iloc[i])][0]
    w_v = TM[visitor][int(df.moods_v.iloc[i])][0]
    if w_h > w_v:
        y_pred[i] = 1

In [17]:
np.abs(y_pred - y_true).mean()

0.4730966041246705

Продвинутая модель.

In [21]:
data = df[df.SEASON > 2006]
y_true = np.array(data.HOME_TEAM_WINS)
data

GAME_DATE_EST   GAME_ID GAME_STATUS_TEXT  HOME_TEAM_ID  VISITOR_TEAM_ID  \
12835    2007-10-06  10700001            Final    1610612738       1610612761   
12834    2007-10-08  10700006            Final    1610612765       1610612748   
12833    2007-10-08  10700005            Final    1610612753       1610612737   
12827    2007-10-09  10700008            Final    1610612749       1610612741   
12826    2007-10-09  10700007            Final    1610612739       1610612764   
...             ...       ...              ...           ...              ...   
5        2022-03-12  22101010            Final    1610612762       1610612758   
4        2022-03-12  22101009            Final    1610612743       1610612761   
3        2022-03-12  22101008            Final    1610612744       1610612749   
1        2022-03-12  22101006            Final    1610612741       1610612739   
0        2022-03-12  22101005            Final    1610612748       1610612750   

       SEASON  TEAM_ID_home  PTS_home  FG_PCT_home  FT_PCT_home  ...  \
12835    2007    1610612738      89.0        0.461        0.696  ...   
12834    2007    1610612765     103.0        0.479        0.714  ...   
12833    2007    1610612753      93.0        0.413        0.560  ...   
12827    2007    1610612749      93.0        0.417        0.651  ...   
12826    2007    1610612739      62.0        0.306        0.800  ...   
...       ...           ...       ...          ...          ...  ...   
5        2021    1610612762     134.0        0.558        0.710  ...   
4        2021    1610612743     115.0        0.551        0.750  ...   
3        2021    1610612744     122.0        0.484        0.933  ...   
1        2021    1610612741     101.0        0.443        0.933  ...   
0        2021    1610612748     104.0        0.398        0.760  ...   

       FG_PCT_away  FT_PCT_away  FG3_PCT_away  AST_away  REB_away  \
12835        0.388        0.625         0.321      21.0      41.0   
12834        0.403        0.739         0.389      22.0      35.0   
12833        0.408        0.702         0.429      19.0      39.0   
12827        0.485        0.600         0.500      24.0      38.0   
12826        0.354        0.690         0.357      17.0      42.0   
...            ...          ...           ...       ...       ...   
5            0.500        0.857         0.394      27.0      33.0   
4            0.471        0.760         0.387      28.0      50.0   
3            0.413        0.696         0.386      27.0      39.0   
1            0.419        0.824         0.208      19.0      40.0   
0            0.422        0.875         0.357      21.0      46.0   

       HOME_TEAM_WINS       date  moods_h  moods_v  moods_diff  
12835               1 2007-10-06      0.0      0.0         0.0  
12834               1 2007-10-08      0.0      0.0         0.0  
12833               0 2007-10-08      0.0      1.0        -1.0  
12827               1 2007-10-09      0.0      0.0         0.0  
12826               0 2007-10-09      0.0      0.0         0.0  
...               ...        ...      ...      ...         ...  
5                   1 2022-03-12      0.0      0.0         0.0  
4                   0 2022-03-12      0.0      1.0        -1.0  
3                   1 2022-03-12      1.0      1.0         0.0  
1                   1 2022-03-12      1.0      0.0         1.0  
0                   0 2022-03-12      1.0      0.0         1.0  

[20198 rows x 25 columns]

In [47]:
k = 1610612737
y_pred = np.zeros(len(data))
for i in range(len(data)):
    home = data.HOME_TEAM_ID.iloc[i] - k
    visitor = data.VISITOR_TEAM_ID.iloc[i] - k
    year = data.SEASON.iloc[i] - 2005
    if w_seasons[year][home] > w_seasons[year][visitor]:
        y_pred[i] = 1

In [48]:
np.abs(y_pred - y_true).mean()

0.4018219625705515

In [55]:
k = 1610612737
y_pred = np.zeros(len(data))
for i in range(len(data)):
    home = df.HOME_TEAM_ID.iloc[i] - k
    visitor = df.VISITOR_TEAM_ID.iloc[i] - k
    year = data.SEASON.iloc[i] - 2005
    w_h = TM_seasons[year][home][int(df.moods_h.iloc[i])][0]
    w_v = TM_seasons[year][visitor][int(df.moods_v.iloc[i])][0]
    if w_h > w_v:
        y_pred[i] = 1

In [56]:
np.abs(y_pred - y_true).mean()

0.4983661748687989